# Generated by Django 4.1.1 on 2022-10-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="allmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Filename", models.CharField(max_length=50)),
                ("Modelname", models.CharField(max_length=50)),
                ("Input", models.CharField(max_length=50)),
                ("Output", models.CharField(max_length=50)),
            ],
        ),
    ]
